ALTER TABLE spells
  ALTER COLUMN school DROP NOT NULL,
  ALTER COLUMN casting_time DROP NOT NULL,
  ALTER COLUMN range DROP NOT NULL,
  ALTER COLUMN duration DROP NOT NULL,
  ALTER COLUMN material_desc DROP NOT NULL,
  ALTER COLUMN description DROP NOT NULL,
  ALTER COLUMN source DROP NOT NULL;
