CREATE TABLE `items` (
	`id` text PRIMARY KEY NOT NULL,
	`system` text NOT NULL,
	`name` text NOT NULL,
	`equipment_category` text NOT NULL,
	`description` text,
	`weight` real,
	`cost` text,
	`weapon_category` text,
	`weapon_range` text,
	`damage_dice_count` integer,
	`damage_die_type` text,
	`damage_type` text,
	`two_handed_dice_count` integer,
	`two_handed_die_type` text,
	`two_handed_damage_type` text,
	`properties` text,
	`range_normal` integer,
	`range_long` integer,
	`armor_category` text,
	`ac_base` integer,
	`ac_dex_bonus` integer DEFAULT true,
	`ac_max_dex` integer,
	`stealth_disadvantage` integer DEFAULT false,
	`str_minimum` integer,
	`source` text DEFAULT 'srd' NOT NULL,
	`user_id` text,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
